bot:
	token: "MTAwMzY4Nzc3MTYxNTAwMjY5NQ.G1UT_H.d5YC6_LHTKlEdjB4udN1dr_vIqI76NKNIGSnyU"
	version: "alpha-pycord"
database:
	host: "192.168.5.222"
	username: "gentchu"
	password: "gentchu"
	dbname: "gentchu"
